package com.example.rojakrecycle.Learn.TOOLS;

import com.example.rojakrecycle.R;

public class UnrecyclableThingsData {

    static String[] rMaterialsName = {
            "Mirrors", "Food waste", "Ceramics", "Plastic wraps", "Styrofoam", "Wood", "Bubble wrap", "Pots"
    };

    static  String[] rMaterialsDesc = {
            //mirrors
            "Mirrors have a reflective coating painted on the back of the glass so you can see your reflection. That coating makes the glass nearly impossible to recycle. Mirror glass is also a hard thing for recyclers to do anything with. To recycle glass, companies have to crush it into small pieces called cullet. The cullet is put in a furnace and combined with a small amount of virgin materials required to make new glass, such as limestone and sand. The furnace heats up to between 2600 degrees and 2800 degrees Fahrenheit depending on the type of glass. Once the glass has been liquefied, it can be poured into new bottles or used for things like beads, kitchen or bathroom tiles and gift items. That temperature difference is the biggest reason why various types of glass cannot be recycled together. Imagine trying to melt together crayons and Styrofoam – two things with very different melting points. The Styrofoam would not melt, and your crayon wax would be ruined because it had giant lumps of garbage in it. The same is true of glass. If you mixed mirror glass with bottle glass, it would render the bottle glass unusable. That explains why it is vitally important to only put certain types of glass in your recycling bin. Almost all curbside recycling providers will tell you to place only bottles and jars in your glass recycling bin. Mirrors, drinking glasses, window glasses, Pyrex dishes, light bulbs and all other types of glass need to stay out. How to recycle mirrors Unless you live in a community with really, really good recycling programs, you will not be able to recycle your mirror. Look into ways to reuse it instead. And if you truly cannot find a way to reuse a broken mirror, please wrap it in newspaper or another heavy paper before placing it in your trash can. That will help protect sanitation workers from getting injured.",
            //food waste
            "While food residue gets burned away during the recycling process for plastic, glass, and metal, the same can’t be said for paper. When paper is recycled, it is mixed with water to form slurry. Oil and fat from food residue don’t mix with water; instead, they float on top of the slurry and mingle with the paper pulp. Oily pulp makes very poor quality paper and is, in effect, unusable. Paper products with grease or food residue, such as pizza boxes, should not be put in the recycling bin. Instead, compost it or just throw it in the trash.\n" +
                    "In single-stream recycling communities, all accepted materials go in the same recycling bin together. This creates the risk of grease or food residue transferring from a plastic, metal, or glass container (which is technically fine to recycle even if it has residue on it) to paper materials (which cannot be recycled if it has residue on it). It’s best to avoid any possible cross-contamination by rinsing soiled recyclables and keeping all food residues out of the bin.\n" +
                    "The biggest reason to keep grease and food residue out of the recycling technically isn’t a recycling issue at all! It’s a sanitary one. Food residue spoils, which can create unsafe conditions for workers in recycling facilities. Prevent mould and bacteria from growing on your recyclables by rinsing them before you put them in the bin.\n",
            //ceramics
            "Fired ceramics are about the same as granite, only more homogenized and quite incapable of further deformation or transformation. Basically, they become inert landfill material or a substrate for growing shellfish in the sea.\n" +
                    "Ceramics start out as clay. It's extremely mouldable depending on its water content. It can be so thin that they can pour it into moulds and make kitchen knives or it can be so thick and stiff that it will hold its shape on a slowly spinning platform and can be manipulated into everything from plates up to giant planters that are almost as tall as you are.\n" +
                    "Once the shape is what is desired it is left to dry out. In this stage clay is pretty hard but also it is very brittle. From this stage you CAN mash it up and soak it in water and return it to how it started.\n" +
                    "Where it changes and becomes useful is it is 'fired'. It is in essence cooked for several hours. The temps it's heated to are pretty extreme, hot enough to turn steel to a complete puddle ( up to 2000 degrees Fahrenheit). Once it is fired it cannot be returned to a mushy, malleable state. The closest you get is wet terracotta chunks.\n",
            //plastic wraps
            "Thin, flimsy, plastic-like bags are difficult to recycle; without specialized equipment they clog machines. And even when plastic wrap is recycled, it's costlier than using virgin materials. When it ends up in landfills or incinerators, both PVC and PVDC can release a highly toxic chemical called dioxin, says the World Health Organization.\n" +
                    "In marine environments, plastic wrap contributes to a larger plastic pollution crisis, but unlike other plastics, scientists are finding that PVC and PVDC do great jobs of picking up bacteria and metals. Those contaminated pieces of microplastic then harm the fish that mistake them for food.\n",
            //styrofoam
            "The problem is the weight. The exact reason that makes Styrofoam, or EPS so attractive to be used as packaging is the same reason it is difficult to recycle. Any profits derived from recycling this material is generated by the value – which is calculated “per pound”. With material this light in weight – it takes a very high value, (and quantity) to cover the cost of transportation, handling, and processing.\n" +
                    "To overcome the issue of “light weight” EPS needs processing before being transported. This can significantly lower the per lb. cost of transportation, and makes it cost effective to recycle. There are two popular methods of densifying this material, either by heating and extrusion, (see picture), or by compressing into logs. Each method allows for cost effective shipping – typically to foreign countries for further processing.\n" +
                    "Equipment used to perform this process can be costly – and must be performed at the point of generation to eliminate handling and transporting loose, bulky material any further than necessary.\n" +
                    "In addition – EPS is a byproduct of oil. When oil prices are high, the value of this material increases. When oil prices drop the price of this material also drops. So, should a large distribution facility, furniture warehouse or fish packing plant generate large amounts of EPS– it can be cost effective to place processing equipment on site. The processed EPS, now that it is densified, has value and is purchased by recyclers because it can be easily and efficiently handled and transported. Without this on site equipment it is not cost effective to recycle EPS.\n",
            //wood
            " Using recycled wood extends the life of the wood so there is no need to use newly sourced wood.  After decades or even centuries of use, wood buildings can be easily adapted or deconstructed and reused, which means they can continue to store carbon indefinitely. Wood can be recycled if it is not contaminated. It should be kept separate from painted, coated and preservative treated wood. Industrial wood comprises of wood waste from the commercial and industrial sectors including the transport sector, building trade suppliers, ship building, cabinet making, and construction and demolition companies.\n" +
                    "There are a variety of preservatives used in Australia for treating wood, which are impregnated into the wood. Humans and the environment can be put at risk if exposed to these chemicals at high enough levels and environmental problems can occur if treated wood is burned without appropriate emission control equipment.\n" +
                    "Although treatment increases its durability, the options for recycling treated wood are limited. It is therefore expected that the quantity of treated timber going to landfill will grow steadily.\n",
            //bubble wrap
            "Bubble wrap is completely recyclable, but cannot be accepted curbside or grouped in with the rest of your home and business recycling.\n" +
                    "Bubble wrap, in particular, is categorized under RIC #4, meaning it’s made up of low-density polyethylene (LDPE). This category and material of plastics should generally not be placed in curbside recycling. In fact, plastic films are known as contaminants to the recycling system. This is because soft LDPEs like bubble wrap can clog the machines that process plastic recycling—posing a threat to both recyclers and their equipment. After being separated from acceptable recyclables (or after causing problems with the equipment), the plastic films will be sent to the landfill. Once in a landfill, it’s estimated that plastic bags can take anywhere from 10-1,000 years to decompose completely.\n" +
                    "However, #4 plastics like bubble wrap are still recyclable, just in a different way. Plastics such as bubble wrap should be grouped with other soft plastics and brought to designated drop-offs for plastic film. Bubble wrap can be recycled alongside other plastic films, like plastic bags, at designated recycling bins. These bins are typically advertised for plastic bag recycling and can be found at most grocery stores.\n",
            //pots
            "Although pots and pans are not hazardous, they are not regularly accepted at local scrap metal recycling centers for cash refunds. This is because many pots and pans have a coat over top of the metal to prevent chemicals from the metal from seeping into food. A well-known example of this type of coat is called Teflon (Polytetrafluoroethylene). Teflon helps prevent food from being contaminated with certain chemicals and prevents food from sticking to the pot or pan. This coating is highly beneficial for cooking, but cannot be recycled at a metal recycling center due to possible environmental hazards.",
    };

    static Integer[] rMaterialsImg = {
            R.drawable.mirrors,
            R.drawable.foodwaste,
            R.drawable.ceramics,
            R.drawable.plasticwrap,
            R.drawable.styrofoam,
            R.drawable.wood,
            R.drawable.bubblewrap,
            R.drawable.pots
    };
    }
