package com.example.rojakrecycle;

import android.content.Intent;

public class RecyclableThingsData {

    static String[] rMaterialsName = {
            "Cellphones", "Glass", "Paper", "Batteries", "Newspaper", "Plastics", "Aluminium cans", "Organics"
    };

    static String[] rMaterialsDesc = {
//            cellphones
            "Much of a typical cell phone is plastic, including the case and some smaller components. There also tends to be glass in the screen, as well as various metals in the circuits, battery, screen, and elsewhere, including aluminium, cadmium, chromium, copper, gold, iron, lead, lithium, nickel, silver, tin, and zinc.\n" +
                    "If a phone is thrown away instead of recycled, it may face greater odds of ending up somewhere unsuitable and causing trouble. On top of the risk of plastic pollution, many of the metals in mobile phones are toxic to humans and other animals, including several with potential carcinogenic effects. In a 2019 study of metals in discarded phones, researchers noted a “statistically significant increase” in the toxic content of smartphones between 2006 and 2015, with the largest carcinogenic risk posed by nickel, lead, and beryllium. Silver, zinc, and copper are also linked to non-cancer health risks, the researchers wrote in the Journal of Hazardous Materials, while copper “dominated ecotoxicity risks” from phones.\n" +
                    "Major cell carriers including AT&T, T-Mobile, and Verizon offer trade-in programs for some older phones that still work, for instance, but also accept ineligible phones for free recycling, either in their stores or by mail. Many manufacturers will also take your old phone off your hands, although some only accept their own products. Apple and Samsung both have trade-in programs for eligible older phones, for example, in some cases offering credit or a gift card in return. Some retailers have trade-in programs, too, including a few big-box electronics and office supply chains as well as online retail giant Amazon. Unusable cell phones also can be charitable donations, thanks to organizations that recycle donated phones and use the proceeds to support various causes.\n",
//            glass
            "Glass recycling, or glass reprocessing, is the process of turning waste glass back into usable products.  This involves washing, crushing and melting used glass before moulding it back into bottles and jars. This cycle can be repeated endlessly with no loss in quality to the end product. Glass manufacturers in the UK recycle almost 70% of all glass packaging sold, the majority of this figure is made up of glass bottle recycling.  All glass collected separately is brought back to our state of the art Materials Recycling Facility (MRF) for storage.  This is then bulked up and transported to a glass treatment plant. The glass goes through a pre-treatment process which removes any paper or plastic using blown air.  Any metal objects are removed with magnets.\n" +
                    "Next, it is sorted by colour and washed to remove any further impurities. Then it’s crushed, melted and moulded into new products such as bottles and jars.  A highly versatile material with almost limitless applications; it makes complete sense to recover as much glass as practically possible. Glass does not degrade through the recycling process so it can be recycled again and again. This is one of the most efficient forms of recycling of any type of commercial waste, with almost 100% recovery of the original material in an extremely clean and pure form, with fantastic environmental benefits.\n" +
                    "Bottles and jars are 100% recyclable, and can be recycled again and again, without any loss of quality, but there are other types of glass products which are manufactured through a different process, and can cause problems if they’re put into the recycling process.  These are listed here below. Some glass cannot be recycled however, such as light bulbs, windows, mirrors, plate glass, eyeglasses, glass art, Pyrex baking dishes, fluorescent lighting tubes, broken glass, drinking glasses, crystal glass.\n",
//            paper
            "After you put paper in your recycling bin, it’s taken to a recycling center where contaminants such as plastic, glass or trash are removed. Next, the paper is sorted into different grades. Once paper is sorted, it will be stored in bales until a mill needs it, and then it will be transferred to the mill for processing. Once at the mill large machines (pulpers) shred the paper into small pieces. This mixture of paper, water, and chemicals is heated and the pieces of paper break down into fibers. The mixture is pressed through a screen to remove adhesives and other remaining contaminants. Next, the paper will be spun in a cone-shaped cylinder to clean it, and sometimes ink will also be removed. At this point, the pulp is sent through a machine that sprays it onto a conveyor belt. Water will drip through the belt’s screen, and the paper fibers will start bonding together. Heated metal rollers will dry the paper, and the paper will be put onto large rolls, which can be made into new paper products.\n" +
                    "The grade of paper is determined by fiber length, which shortens after each trip through the recycling process. After being recycled five to seven times, the fibers become too short to make new paper and will need to be mixed with virgin fibers, according to the EPA. Ever heard that paper has “seven generations”? That phrase refers to how many times paper can be recycled before its fibers become too short. There are five basic paper grade categories, according to the EPA. While these terms may be most useful to paper mills looking to process certain kinds of paper, you may hear these terms once in a while, and it’s possible you’ll need to be able to distinguish between them.\n" +
                    "Old Corrugated Containers – You might know this as “corrugated cardboard.” It’s most often found in boxes and product packaging.\n" +
                    "Mixed Paper – This is a broad category of paper that includes things like mail, catalogs, phone books and magazines.\n" +
                    "Old Newspapers – This one is pretty self-explanatory. Mills use newspapers, a lower grade paper, to make more newsprint, tissue and other products.\n" +
                    "High Grade Deinked Paper – This quality paper consists of things like envelopes, copy paper and letterhead that has gone through the printing process and had the ink removed.\n" +
                    "Pulp Substitutes – This paper is usually discarded scraps from mills, and you probably won’t have to worry about running into it, though it may find its way into products you buy.\n",
//            batteries
            "Batteries contain a number of heavy metals and toxic chemicals and disposing of them by the same process as regular household waste has raised concerns over soil contamination and water pollution. Lead-acid batteries include but are not limited to: car batteries, golf cart batteries, UPS batteries, industrial fork-lift batteries, motorcycle batteries, and commercial batteries. These are recycled by grinding them, neutralizing the acid, and separating the polymers from the lead. The recovered materials are used in a variety of applications, including new batteries. \n" +
                    "Silver oxide batteries are used most frequently in watches, toys, and some medical devices, silver oxide batteries contain a small amount of mercury. Most jurisdictions regulate their handling and disposal to reduce the discharge of mercury into the environment. Silver oxide batteries can be recycled to recover the mercury.\n" +
                    "Lithium-ion batteries and lithium iron phosphate (LiFePO4) batteries often contain among other useful metals high-grade copper and aluminium in addition to – depending on the active material – transition metals cobalt and nickel as well as rare earths. To prevent a future shortage of cobalt, nickel, and lithium and to enable a sustainable life cycle of these technologies, recycling processes for lithium batteries are needed. These processes have to regain not only cobalt, nickel, copper, and aluminium from spent battery cells, but also a significant share of lithium. \n" +
                    "These steps are: Deactivation or discharging of the battery (especially in case of batteries from electric vehicles), Disassembly of battery systems (especially in case of batteries from electric vehicles), Mechanical processes (including crushing, sorting, and sieving processes), Electrolyte recovery, Hydrometallurgical processes, Pyrometallurgical processes and lastly recycling the lead from batteries.\n",
//            newspaper
            "One of the most common items recycled all across the globe is old newspapers. Hundreds of tons of waste paper is collected daily from homes, offices, etc. There was a time when they were disposed by burning or dumping them in landfills. Nowadays, the best and most eco-friendly way to get rid of old papers is to recycle them so that they can used again for different purposes.\n" +
                    "When you recycle unwanted newspapers, magazines, books, etc. you contribute to the reduction of waste materials that are sent to incinerators and landfills. This in turn minimizes the emission of harmful gases such as methane into the environment. 37 per cent of the output of methane gas is from landfills so by recycling organic materials like paper, anaerobic decomposition and methane gas production is significantly reduced. You protect the environment against pollution and damage by recycling waste paper.\n" +
                    "Recycling old newspapers is also a wonderful way to conserve the few natural resources left on the planet. As you know, the manufacture of paper requires timber which is one of the reasons why multitudes of trees are felled every year.  When paper is recycled, you help in the conservation of timber, minerals and water. When a ton of paper is recycled every year, 7000 gallons of water and 17 trees are saved.\n",
//            plastics
            "Plastic recycling is the reprocessing of plastic waste into new and useful products. When performed correctly, this can reduce dependence on landfill, conserve resources and protect the environment from plastic pollution and greenhouse gas emissions. Although recycling rates are increasing, they lag behind those of other recoverable materials, such as aluminium, glass and paper. The global recycling rate in 2015 was 19.5%, while 25.5% was incinerated and the remaining 55% disposed of to landfill. Since the beginning of plastic production in the 20th century, until 2015, the world has produced some 6.3 billion tonnes of plastic waste, only 9% of which has been recycled, and only ~1% has been recycled more than once.\n" +
                    "Recycling is necessary because almost all plastic is non-biodegradable and thus builds-up in the environment, where it can cause harm. For example, approximately 8 million tons of waste plastic enter the Earth's oceans every year, causing damage to the aquatic ecosystem and forming large ocean garbage patches.\n" +
                    "Presently, almost all recycling is performed by remelting and reforming used plastic into new items; so-called mechanical recycling. This can cause polymer degradation at a chemical level, and also requires that waste be sorted by both colour and polymer type before being reprocessed, which is complicated and expensive. Failures in this can lead to material with inconsistent properties, which is unappealing to industry.\n" +
                    "In an alternative approach known as feedstock recycling, waste plastic is converted back into its starting chemicals, which can then be reprocessed back into fresh plastic. This offers the hope of greater recycling but suffers from higher energy and capital costs. Waste plastic can also be burnt in place of fossil fuels as part of energy recovery. This is a controversial practice, but is nonetheless performed on a large scale. In some countries, it is the dominant form of plastic waste disposal, particularly where landfill diversion policies are in place.\n",
//            aluminium cams
            "Aluminium cans are very common in our daily life and is often consumed as drink containers and later thrown as garbage in bins or being littered on streets and open plots. The good thing is that these cans provide source of food and income to many poor people who resort to collect them from the bins and open areas and sell it to the middle recycling shops in exchange of money. This practice is certainly restricting huge quantities of cans going to municipal landfill sites saving valuable space and is prompting informal recyclable material collection.\n" +
                    "The aluminium can is the world’s most recycled packaging container. We need to understand that all aluminium cans are 100% recyclable. It can take up to 500 years for aluminium cans to decompose. Aluminium does not degrade during the recycling process, which means it can be repeatedly recycled many a times. Recycling aluminium saves millions of tonnes of greenhouse gases, energy, electricity and fuel for its transportation. Making aluminium cans from recycled materials requires less than 5% of the energy used to make new aluminium cans from Bauxite.\n" +
                    "The recycling of aluminium generally produces significant cost savings over the production of new aluminium even when the cost of collection, separation and recycling are taken into account. Over the long term, even larger national savings are made when the reduction in the capital costs associated with landfills, mines and international shipping of raw aluminium are considered.\n" +
                    "It is our environmental and social duty to separate aluminium cans from other domestic waste and either give to recyclers or separately discard it at bins, so that it can be easily collected by poor iterants. Before disposal, ensure that the aluminium cans are empty and not soiled and damaged. The collected cans in the Middle East are then taken to a local recycling facility where they are crushed, compacted, baled and later transported and exported to other countries for recycling, where they are milled and remade into new products.\n" +
                    "An important fact is that recycling an aluminium can saves enough energy to run a television for three hours. If we throw away two aluminium cans, we waste more energy than is used daily by each of the billion human beings in the developing world.\n",
//            organics
            "You may have seen new bins around your community featuring signs that say \"organics only,\" but what does that mean? Organics recycling is the recycling of organic material- anything that was once alive- into compost, a special soil amendment. Composting happens naturally and requires very little energy input. Organics recycling plays a key role in keeping valuable materials out of landfills.\n" +
                    "About 30% of what we usually throw away is actually organics including food scraps and food-soiled paper products. The organics recycling you see in your community is different than backyard composting because the organics are brought to a specialized recycling facility. This facility will line up the organics in windrows which creates more heat than you would find in your backyard. Because of this, things such as bones, meat, and paper-products can go in these bins. \n" +
                    "First and foremost, waste should always be reduced. If that is not possible, reusing is the next best thing. Only if we cannot reduce and reuse should we recycle or compost. Of course if the item is not recyclable or compostable such as but not limited to chip bags, Styrofoam, and/or pet waste, then it must go in the trash. Reducing is especially important when it comes to buying food. Currently, in the United States, we are wasting as much as 40% of all of our food. Although composting is a great solution to preventing food scraps from entering the landfill, it is not the best solution to the food waste problem. \n",
    };

    static Integer[] rMaterialsImg = {
            R.drawable.cellphones,
            R.drawable.glass,
            R.drawable.paper,
            R.drawable.batteries,
            R.drawable.newspaper,
            R.drawable.plastics,
            R.drawable.aluminiumcans,
            R.drawable.organics
    };
}
